# Generated by Django 3.1.6 on 2021-02-10 17:27

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('tags', models.CharField(default='gl-all-python,gl-junior', max_length=500)),
                ('recommended_time', models.SmallIntegerField(default=2)),
                ('description', tinymce.models.HTMLField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('hr_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('is_answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.question')),
            ],
            options={
                'unique_together': {('letter', 'question')},
            },
        ),
    ]
