# Generated by Django 3.1.6 on 2021-02-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hr_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
