# Generated by Django 3.1.6 on 2021-02-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20210210_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
