# Generated by Django 3.1.6 on 2021-02-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20210210_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['question', 'letter']},
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(1, 'Registered'), (2, 'Uploaded'), (3, 'Updated'), (4, 'Failed')], default=1),
        ),
    ]
